# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir f:/ma703/a703_100t/07/axi_ddr_5640/user_src/msxbo_ovsensorrgb565_1.0/prj/msxbo_ovsensorrgb565_v1_0_project/MSXBO_OVSensorRGB565_v1_0_project.cache/wt [current_project]
set_property parent.project_path f:/ma703/a703_100t/07/axi_ddr_5640/user_src/msxbo_ovsensorrgb565_1.0/prj/msxbo_ovsensorrgb565_v1_0_project/MSXBO_OVSensorRGB565_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/MA703/A703_100T/07/AXI_DDR_5640/user_src [current_project]
set_property ip_output_repo f:/ma703/a703_100t/07/axi_ddr_5640/user_src/msxbo_ovsensorrgb565_1.0/prj/msxbo_ovsensorrgb565_v1_0_project/MSXBO_OVSensorRGB565_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib f:/MA703/A703_100T/07/AXI_DDR_5640/user_src/MSXBO_OVSensorRGB565_1.0/IPSRC/MSXBO_OVSensorRGB565.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top MSXBO_OVSensorRGB565 -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MSXBO_OVSensorRGB565.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MSXBO_OVSensorRGB565_utilization_synth.rpt -pb MSXBO_OVSensorRGB565_utilization_synth.pb"
