#------------------------bit compress spix4 speed up-----------------------------------
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
#set_property BITSTREAM.CONFIG.NEXT_CONFIG_ADDR 0x01000000 [current_design]
set_property BITSTREAM.CONFIG.TIMER_CFG 0x20000 [current_design] 
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
##--------------------------SPIX4--------------------------------------------
set_property PACKAGE_PIN B24 [get_ports qspi_d0] 
set_property PACKAGE_PIN A25 [get_ports qspi_d1]  
set_property PACKAGE_PIN B22 [get_ports qspi_d2]  
set_property PACKAGE_PIN A22 [get_ports qspi_d3]    
set_property PACKAGE_PIN C23 [get_ports qspi_csb]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_d0]    
set_property IOSTANDARD LVCMOS33 [get_ports qspi_d1]  
set_property IOSTANDARD LVCMOS33 [get_ports qspi_d2]    
set_property IOSTANDARD LVCMOS33 [get_ports qspi_d3]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_csb]
#-----------------------CLK SIGNAL-----------------------------------------
set_property PACKAGE_PIN AA3 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS15 [get_ports sys_clk]
create_clock -period 10.000 -name sys_clk -waveform {0.000 5.000} [get_ports sys_clk]
set_property PACKAGE_PIN D23 [get_ports FPGA_50M]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_50M]
#set_property PACKAGE_PIN G22 [get_ports FPGA_ACLK]
#set_property IOSTANDARD LVCMOS33 [get_ports FPGA_ACLK]
#-------------------------dac_gain pin------------------------------
set_property PACKAGE_PIN E18 [get_ports AOUT1_CON]
set_property PACKAGE_PIN D18 [get_ports AOUT2_CON]
set_property IOSTANDARD LVCMOS33 [get_ports AOUT1_CON]
set_property IOSTANDARD LVCMOS33 [get_ports AOUT2_CON]
##-------------------------adc_gain pin------------------------------
set_property PACKAGE_PIN L19 [get_ports AIN4_PD]
set_property PACKAGE_PIN L20 [get_ports AIN4_RELAY2]
set_property PACKAGE_PIN G17 [get_ports AIN4_RELAY1]
set_property PACKAGE_PIN F18 [get_ports AIN3_PD]
set_property PACKAGE_PIN F17 [get_ports AIN3_RELAY2]
set_property PACKAGE_PIN E17 [get_ports AIN3_RELAY1]
set_property PACKAGE_PIN J15 [get_ports AIN2_PD]
set_property PACKAGE_PIN J16 [get_ports AIN2_RELAY2]
set_property PACKAGE_PIN E15 [get_ports AIN2_RELAY1]
set_property PACKAGE_PIN E16 [get_ports AIN1_PD]
set_property PACKAGE_PIN K16 [get_ports AIN1_RELAY2]
set_property PACKAGE_PIN K17 [get_ports AIN1_RELAY1]
set_property IOSTANDARD LVCMOS33 [get_ports AIN4_PD]
set_property IOSTANDARD LVCMOS33 [get_ports AIN4_RELAY2]
set_property IOSTANDARD LVCMOS33 [get_ports AIN4_RELAY1]
set_property IOSTANDARD LVCMOS33 [get_ports AIN3_PD]
set_property IOSTANDARD LVCMOS33 [get_ports AIN3_RELAY2]
set_property IOSTANDARD LVCMOS33 [get_ports AIN3_RELAY1]
set_property IOSTANDARD LVCMOS33 [get_ports AIN2_PD]
set_property IOSTANDARD LVCMOS33 [get_ports AIN2_RELAY2]
set_property IOSTANDARD LVCMOS33 [get_ports AIN2_RELAY1]
set_property IOSTANDARD LVCMOS33 [get_ports AIN1_PD]
set_property IOSTANDARD LVCMOS33 [get_ports AIN1_RELAY2]
set_property IOSTANDARD LVCMOS33 [get_ports AIN1_RELAY1]
#----------------------------offset dac----------------------------------
set_property PACKAGE_PIN E22 [get_ports ADC1_SDA]
set_property PACKAGE_PIN D21 [get_ports ADC2_SCL]
set_property PACKAGE_PIN C22 [get_ports ADC2_SDA]
set_property PACKAGE_PIN C21 [get_ports ADC1_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_SCL]
#-----------------------baseboard signal---------------------------------
set_property PACKAGE_PIN A18 [get_ports LED[0]]
set_property PACKAGE_PIN A19 [get_ports LED[1]]
set_property PACKAGE_PIN H17 [get_ports LED[2]]
set_property PACKAGE_PIN H18 [get_ports LED[3]]
set_property PACKAGE_PIN C17 [get_ports LED[4]]
set_property PACKAGE_PIN C18 [get_ports LED[5]]
set_property PACKAGE_PIN B17 [get_ports LED[6]]
set_property PACKAGE_PIN A17 [get_ports LED[7]]
set_property PACKAGE_PIN G20 [get_ports FAN[0]]
set_property PACKAGE_PIN D19 [get_ports FAN[1]]
set_property PACKAGE_PIN D20 [get_ports UART_RX]
set_property PACKAGE_PIN F19 [get_ports UART_TX]
set_property PACKAGE_PIN E20 [get_ports UART_EN]
set_property PACKAGE_PIN C19 [get_ports FRAM_SCL]
set_property PACKAGE_PIN B19 [get_ports FRAM_SDA]
set_property PACKAGE_PIN G16 [get_ports TRIGGER_OUT]
set_property PACKAGE_PIN D15 [get_ports TRIGGER_IN]
set_property PACKAGE_PIN G15 [get_ports TRIG_CLOCK]
set_property PACKAGE_PIN F15 [get_ports TRIGGER_H]
set_property PACKAGE_PIN C16 [get_ports TRIG_V]
set_property PACKAGE_PIN B16 [get_ports TRIG_BLANK]
set_property IOSTANDARD LVCMOS33 [get_ports LED[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[7]]
set_property IOSTANDARD LVCMOS33 [get_ports FAN[0]]
set_property IOSTANDARD LVCMOS33 [get_ports FAN[1]]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_EN]
set_property IOSTANDARD LVCMOS33 [get_ports FRAM_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports FRAM_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports TRIGGER_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports TRIGGER_IN]
set_property IOSTANDARD LVCMOS33 [get_ports TRIG_CLOCK]
set_property IOSTANDARD LVCMOS33 [get_ports TRIGGER_H]
set_property IOSTANDARD LVCMOS33 [get_ports TRIG_V]
set_property IOSTANDARD LVCMOS33 [get_ports TRIG_BLANK]
#--------------------------AD9517--------------------------------------sync && pd======HHHHHH
set_property PACKAGE_PIN G19 [get_ports pll_csn]
set_property PACKAGE_PIN F20 [get_ports pll_sclk]
set_property PACKAGE_PIN K20 [get_ports pll_sdo]
set_property PACKAGE_PIN J20 [get_ports pll_sdio]
set_property PACKAGE_PIN J18 [get_ports pll_ref_sel]
set_property PACKAGE_PIN J19 [get_ports pll_ld]
set_property PACKAGE_PIN K18 [get_ports pll_resetn]
set_property IOSTANDARD LVCMOS33 [get_ports pll_csn]
set_property IOSTANDARD LVCMOS33 [get_ports pll_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports pll_sdo]
set_property IOSTANDARD LVCMOS33 [get_ports pll_sdio]
set_property IOSTANDARD LVCMOS33 [get_ports pll_ref_sel]
set_property IOSTANDARD LVCMOS33 [get_ports pll_ld]
set_property IOSTANDARD LVCMOS33 [get_ports pll_resetn]
#----------------------------AD9747---------------------------------------
set_property PACKAGE_PIN B21 [get_ports dac_reset]
set_property PACKAGE_PIN B20 [get_ports dac_csb]
set_property PACKAGE_PIN A20 [get_ports dac_sclk]
set_property PACKAGE_PIN M17 [get_ports dac_sdio]
set_property PACKAGE_PIN L18 [get_ports dac_sdo]
set_property PACKAGE_PIN E10 [get_ports dac_dco]
set_property PACKAGE_PIN H22 [get_ports dac_p1d[15]]
set_property PACKAGE_PIN J21 [get_ports dac_p1d[14]]
set_property PACKAGE_PIN G21 [get_ports dac_p1d[13]]
set_property PACKAGE_PIN H21 [get_ports dac_p1d[12]]
set_property PACKAGE_PIN J23 [get_ports dac_p1d[11]]
set_property PACKAGE_PIN K23 [get_ports dac_p1d[10]]
set_property PACKAGE_PIN H24 [get_ports dac_p1d[9]]
set_property PACKAGE_PIN H23 [get_ports dac_p1d[8]]
set_property PACKAGE_PIN J25 [get_ports dac_p1d[7]]
set_property PACKAGE_PIN J24 [get_ports dac_p1d[6]]
set_property PACKAGE_PIN H26 [get_ports dac_p1d[5]]
set_property PACKAGE_PIN J26 [get_ports dac_p1d[4]]
set_property PACKAGE_PIN E26 [get_ports dac_p1d[3]]
set_property PACKAGE_PIN F25 [get_ports dac_p1d[2]]
set_property PACKAGE_PIN A24 [get_ports dac_p1d[1]]
set_property PACKAGE_PIN A23 [get_ports dac_p1d[0]]
set_property PACKAGE_PIN A8 [get_ports dac_p2d[15]]
set_property PACKAGE_PIN A9 [get_ports dac_p2d[14]]
set_property PACKAGE_PIN A10 [get_ports dac_p2d[13]]
set_property PACKAGE_PIN B10 [get_ports dac_p2d[12]]
set_property PACKAGE_PIN B9 [get_ports dac_p2d[11]]
set_property PACKAGE_PIN C9 [get_ports dac_p2d[10]]
set_property PACKAGE_PIN B11 [get_ports dac_p2d[9]]
set_property PACKAGE_PIN B12 [get_ports dac_p2d[8]]
set_property PACKAGE_PIN F8 [get_ports dac_p2d[7]]
set_property PACKAGE_PIN F9 [get_ports dac_p2d[6]]
set_property PACKAGE_PIN G9 [get_ports dac_p2d[5]]
set_property PACKAGE_PIN G10 [get_ports dac_p2d[4]]
set_property PACKAGE_PIN G14 [get_ports dac_p2d[3]]
set_property PACKAGE_PIN H14 [get_ports dac_p2d[2]]
set_property PACKAGE_PIN J10 [get_ports dac_p2d[1]]
set_property PACKAGE_PIN J11 [get_ports dac_p2d[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_csb]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sdo]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sdio]
set_property IOSTANDARD LVCMOS33 [get_ports dac_dco]
set_property IOSTANDARD LVCMOS33 [get_ports dac_reset]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[15]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[14]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[13]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[12]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[11]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[10]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[9]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[8]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[7]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[6]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[5]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[4]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p1d[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[15]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[14]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[13]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[12]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[11]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[10]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[9]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[8]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[7]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[6]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[5]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[4]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_p2d[0]]
create_clock -period 20.000 -name dac_dco -waveform {0.000 10.000} [get_ports dac_dco]
#-------------------------first AD9258--------------------------------
set_property PACKAGE_PIN J13 [get_ports adc1_dea]
set_property PACKAGE_PIN H13 [get_ports adc1_deb]
set_property PACKAGE_PIN G11 [get_ports adc1_oeb]
set_property PACKAGE_PIN F10 [get_ports adc1_pwdn]
set_property PACKAGE_PIN H12 [get_ports adc1_csb]
set_property PACKAGE_PIN H11 [get_ports adc1_sdio]
set_property PACKAGE_PIN F14 [get_ports adc1_sclk]
set_property PACKAGE_PIN F13 [get_ports adc1_ora]
set_property PACKAGE_PIN G12 [get_ports adc1_orb]
set_property PACKAGE_PIN Y22 [get_ports adc1_dcoa]
set_property PACKAGE_PIN AA23 [get_ports adc1_dcob]
set_property PACKAGE_PIN P18 [get_ports adc1_da[15]]
set_property PACKAGE_PIN R18 [get_ports adc1_da[14]]
set_property PACKAGE_PIN R17 [get_ports adc1_da[13]]
set_property PACKAGE_PIN R16 [get_ports adc1_da[12]]
set_property PACKAGE_PIN N17 [get_ports adc1_da[11]]
set_property PACKAGE_PIN P16 [get_ports adc1_da[10]]
set_property PACKAGE_PIN R20 [get_ports adc1_da[9]]
set_property PACKAGE_PIN T20 [get_ports adc1_da[8]]
set_property PACKAGE_PIN U20 [get_ports adc1_da[7]]
set_property PACKAGE_PIN U19 [get_ports adc1_da[6]]
set_property PACKAGE_PIN T19 [get_ports adc1_da[5]]
set_property PACKAGE_PIN T18 [get_ports adc1_da[4]]
set_property PACKAGE_PIN T23 [get_ports adc1_da[3]]
set_property PACKAGE_PIN T22 [get_ports adc1_da[2]]
set_property PACKAGE_PIN T17 [get_ports adc1_da[1]]
set_property PACKAGE_PIN U17 [get_ports adc1_da[0]]
set_property PACKAGE_PIN P20 [get_ports adc1_db[15]]
set_property PACKAGE_PIN P19 [get_ports adc1_db[14]]
set_property PACKAGE_PIN M26 [get_ports adc1_db[13]]
set_property PACKAGE_PIN N26 [get_ports adc1_db[12]]
set_property PACKAGE_PIN T25 [get_ports adc1_db[11]]
set_property PACKAGE_PIN T24 [get_ports adc1_db[10]]
set_property PACKAGE_PIN P26 [get_ports adc1_db[9]]
set_property PACKAGE_PIN R26 [get_ports adc1_db[8]]
set_property PACKAGE_PIN V22 [get_ports adc1_db[7]]
set_property PACKAGE_PIN U22 [get_ports adc1_db[6]]
set_property PACKAGE_PIN V24 [get_ports adc1_db[5]]
set_property PACKAGE_PIN V23 [get_ports adc1_db[4]]
set_property PACKAGE_PIN W21 [get_ports adc1_db[3]]
set_property PACKAGE_PIN V21 [get_ports adc1_db[2]]
set_property PACKAGE_PIN W24 [get_ports adc1_db[1]]
set_property PACKAGE_PIN W23 [get_ports adc1_db[0]]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_dea]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_deb]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_oeb]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_csb]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_sdio]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_ora]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_orb]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_dcoa]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_dcob]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[15]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[14]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[13]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[12]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[11]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[10]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[9]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[8]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[7]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[6]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[5]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[4]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[3]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[2]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[1]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_da[0]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[15]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[14]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[13]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[12]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[11]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[10]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[9]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[8]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[7]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[6]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[5]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[4]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[3]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[2]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[1]]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_db[0]]
create_clock -period 20.000 -name adc1_dcoa -waveform {0.000 10.000} [get_ports adc1_dcoa]
create_clock -period 20.000 -name adc1_dcob -waveform {0.000 10.000} [get_ports adc1_dcob]
#----------------------second AD9258-------------------------------
set_property PACKAGE_PIN H9 [get_ports adc2_dea]
set_property PACKAGE_PIN H8 [get_ports adc2_deb]
set_property PACKAGE_PIN F12 [get_ports adc2_oeb]
set_property PACKAGE_PIN D9 [get_ports adc2_pwdn]
set_property PACKAGE_PIN D8 [get_ports adc2_csb]
set_property PACKAGE_PIN E11 [get_ports adc2_sdio]
set_property PACKAGE_PIN D11 [get_ports adc2_sclk]
set_property PACKAGE_PIN C14 [get_ports adc2_ora]
set_property PACKAGE_PIN C13 [get_ports adc2_orb]
set_property PACKAGE_PIN Y23 [get_ports adc2_dcoa]
set_property PACKAGE_PIN AC23 [get_ports adc2_dcob]
set_property PACKAGE_PIN AC21 [get_ports adc2_da[15]]
set_property PACKAGE_PIN AB21 [get_ports adc2_da[14]]
set_property PACKAGE_PIN Y21 [get_ports adc2_da[13]]
set_property PACKAGE_PIN W20 [get_ports adc2_da[12]]
set_property PACKAGE_PIN AC22 [get_ports adc2_da[11]]
set_property PACKAGE_PIN AB22 [get_ports adc2_da[10]]
set_property PACKAGE_PIN AF25 [get_ports adc2_da[9]]
set_property PACKAGE_PIN AF24 [get_ports adc2_da[8]]
set_property PACKAGE_PIN AF23 [get_ports adc2_da[7]]
set_property PACKAGE_PIN AE23 [get_ports adc2_da[6]]
set_property PACKAGE_PIN AE21 [get_ports adc2_da[5]]
set_property PACKAGE_PIN AD21 [get_ports adc2_da[4]]
set_property PACKAGE_PIN AF22 [get_ports adc2_da[3]]
set_property PACKAGE_PIN AE22 [get_ports adc2_da[2]]
set_property PACKAGE_PIN AD24 [get_ports adc2_da[1]]
set_property PACKAGE_PIN AD23 [get_ports adc2_da[0]]
set_property PACKAGE_PIN V26 [get_ports adc2_db[15]]
set_property PACKAGE_PIN U26 [get_ports adc2_db[14]]
set_property PACKAGE_PIN U25 [get_ports adc2_db[13]]
set_property PACKAGE_PIN U24 [get_ports adc2_db[12]]
set_property PACKAGE_PIN W26 [get_ports adc2_db[11]]
set_property PACKAGE_PIN W25 [get_ports adc2_db[10]]
set_property PACKAGE_PIN Y26 [get_ports adc2_db[9]]
set_property PACKAGE_PIN Y25 [get_ports adc2_db[8]]
set_property PACKAGE_PIN AC26 [get_ports adc2_db[7]]
set_property PACKAGE_PIN AB26 [get_ports adc2_db[6]]
set_property PACKAGE_PIN AB25 [get_ports adc2_db[5]]
set_property PACKAGE_PIN AA25 [get_ports adc2_db[4]]
set_property PACKAGE_PIN AE26 [get_ports adc2_db[3]]
set_property PACKAGE_PIN AD26 [get_ports adc2_db[2]]
set_property PACKAGE_PIN AE25 [get_ports adc2_db[1]]
set_property PACKAGE_PIN AD25 [get_ports adc2_db[0]]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_dea]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_deb]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_oeb]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_csb]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_sdio]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_ora]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_orb]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_dcoa]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_dcob]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[15]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[14]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[13]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[12]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[11]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[10]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[9]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[8]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[7]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[6]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[5]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[4]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[3]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[2]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[1]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_da[0]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[15]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[14]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[13]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[12]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[11]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[10]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[9]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[8]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[7]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[6]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[5]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[4]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[3]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[2]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[1]]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_db[0]]
create_clock -period 20.000 -name adc2_dcoa -waveform {0.000 10.000} [get_ports adc2_dcoa]
create_clock -period 20.000 -name adc2_dcob -waveform {0.000 10.000} [get_ports adc2_dcob]
##-------------------------PCIE--------------------------------------------------------
#set_property PACKAGE_PIN A12 [get_ports pcie_resetn]
#set_property IOSTANDARD LVCMOS33 [get_ports pcie_resetn]
#set_property PACKAGE_PIN K6 [get_ports {pcie_sys_clk_clk_p}]
#create_clock -period 10.000 -name pcie_sys_clk [get_ports {pcie_sys_clk_clk_p}]
##------------------------MGTX8-------------------------------------------------------
#set_property PACKAGE_PIN H2 [get_ports {pcie_mgt_txp[0]}]
#set_property PACKAGE_PIN K2 [get_ports {pcie_mgt_txp[1]}]
#set_property PACKAGE_PIN M2 [get_ports {pcie_mgt_txp[2]}]
#set_property PACKAGE_PIN P2 [get_ports {pcie_mgt_txp[3]}]
#set_property PACKAGE_PIN A4 [get_ports {pcie_mgt_txp[4]}]
#set_property PACKAGE_PIN B2 [get_ports {pcie_mgt_txp[5]}]
#set_property PACKAGE_PIN D2 [get_ports {pcie_mgt_txp[6]}]
#set_property PACKAGE_PIN F2 [get_ports {pcie_mgt_txp[7]}]
#set_property PACKAGE_PIN J4 [get_ports {pcie_mgt_rxp[0]}]
#set_property PACKAGE_PIN L4 [get_ports {pcie_mgt_rxp[1]}]
#set_property PACKAGE_PIN N4 [get_ports {pcie_mgt_rxp[2]}]
#set_property PACKAGE_PIN R4 [get_ports {pcie_mgt_rxp[3]}]
#set_property PACKAGE_PIN B6 [get_ports {pcie_mgt_rxp[4]}]
#set_property PACKAGE_PIN C4 [get_ports {pcie_mgt_rxp[5]}]
#set_property PACKAGE_PIN E4 [get_ports {pcie_mgt_rxp[6]}]
#set_property PACKAGE_PIN G4 [get_ports {pcie_mgt_rxp[7]}]

#-------------------------ETHERNET--------------------------------------------------------
set_property PACKAGE_PIN D6 [get_ports {gtrefclk_p}]
#set_property PACKAGE_PIN F5 [get_ports {gtrefclk_p}]
create_clock -period 8.000 -name gtrefclk [get_ports {gtrefclk_p}]

set_property PACKAGE_PIN A4 [get_ports txp_sgmii]
#set_property PACKAGE_PIN A3 [get_ports txn_sgmii]
#set_property PACKAGE_PIN B6 [get_ports rxp_sgmii]
#set_property PACKAGE_PIN B5 [get_ports rxn_sgmii]
set_property PACKAGE_PIN B15 [get_ports PHY_RESETn]
set_property PACKAGE_PIN A13 [get_ports PHY_INTn]
set_property PACKAGE_PIN B14 [get_ports PHY_MDC]
set_property PACKAGE_PIN A14 [get_ports PHY_MDIO]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RESETn]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_INTn]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_MDIO]

set_false_path -to [get_pins -filter {REF_PIN_NAME =~ PRE} -of [get_cells -hier -regexp {.*\/reset_sync.*}]]
# control signal is synched separately so this is a false path
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/rd_addr_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 3.200
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/wr_store_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *fifo_i/resync_wr_store_frame_tog/data_sync_reg0}] 3.200
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/update_addr_tog_reg}] -to [get_cells -hier -filter {name =~ *rx_fifo_i/sync_rd_addr_tog/data_sync_reg0}] 3.200
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_addr_txfer_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 3.200
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frame_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frame_in_fifo/data_sync_reg0}] 3.200
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frames_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frames_in_fifo/data_sync_reg0}] 3.200
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/frame_in_fifo_valid_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_fif_valid_tog/data_sync_reg0}] 3.200
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_txfer_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_txfer_tog/data_sync_reg0}] 3.200
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_tran_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_tran_frame_tog/data_sync_reg0}] 3.200
set_power_opt -exclude_cells [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ *.bram.* }]
# Control Gray Code delay and skew across clock boundary
#set_false_path -to [get_pins -hier -filter {name =~ *tx_elastic_buffer_inst/reclock_rd_addrgray*/data_sync*/D}]
#set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/reclock_rd_addrgray*/data_sync*}] -filter {REF_PIN_NAME =~ D}]
##set_false_path -to [get_pins -hier -filter {name =~ *tx_elastic_buffer_inst/reclock_wr_addrgray*/data_sync*/D}]
#set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/reclock_wr_addrgray*/data_sync*}] -filter {REF_PIN_NAME =~ D}]
# Constrain between Distributed Memory (output data) and the 1st set of flip-flops
##set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -hier -filter {name =~ tx_elastic_buffer_inst/tx_en_fifo_reg1*/D}]
#set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/tx_en_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]
##set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -hier -filter {name =~ tx_elastic_buffer_inst/tx_er_fifo_reg1*/D}]
#set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/tx_er_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]
##set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -hier -filter {name =~ tx_elastic_buffer_inst/txd_fifo_reg1*/D}]
#set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/txd_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -to [get_pins -hier -filter {name =~ *reset_sync*/PRE }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *reset_sync*}] -filter {REF_PIN_NAME =~ PRE}]
#set_false_path -to [get_pins */core_resets_i/pma_reset_pipe_reg*/PRE]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *core_resets_i/pma_reset_pipe_reg*}] -filter {REF_PIN_NAME =~ PRE}]
#set_false_path -to [get_pins */core_resets_i/pma_reset_pipe*[0]/D]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *core_resets_i/pma_reset_pipe*[0]}] -filter {REF_PIN_NAME =~ D}]

#DCI
set_property DCI_CASCADE {32 34} [get_iobanks 33]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]

set_false_path -from [get_clocks clk_pll_i] -to [get_clocks clkout0]
set_false_path -from [get_clocks clkout0] -to [get_clocks clk_pll_i]